return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "black",
        "isort",
        "autoflake",
        "ruff-lsp",
        "ruff",
        "jedi-language-server",
        "fortls",
        "prettierd",
        "latexindent",
        "texlab",
        "tectonic",
        "ltex-ls",
        "markdownlint",
        "cmake-language-server",
        "cmakelint",
        "bash-language-server",
        "shellharden",
        "clang-format",
        "clangd",
        "cpptools",
        "yaml-language-server",
      },
    },
  },
}
